### PR TITLE
ADD MIT LICENSE FOR ISSUE #93

### PR DESCRIPTION
**Pull request by PILOTEZEBS**
### J'ai terminer de résoudre l'issue #93 en ajoutant toute les licence sur chaque fichier JAVA et c est prêt pour le merge.

by<a href="https://github.com/PILOTEZEBS">@PILOTEZEBS</a>

### CODE REVIEW

**Comment by elhmn** [comment]
Great job adding these. However I think adding license in every single file does not seem relevant for an MIT licence as the license is extremely permissive and does not require to be added to every files. Additionally doing that will force every single developer to add this header to the file, and this can become an extremely annoying process unless it is automated or they are provided a tool that allow them to add this header quickly.

@FanJups andn @SalathielGenese , what do you both think about ☝️

**Comment by FanJups** [comment]
Ok, we'll see if it is still needed to do it before deploying the project.

**Comment by FanJups** [comment]
For now, let's keep this, we have a lot of work to do, some classes will disappear others will be created... Let's think about it later.

**Review by FanJups — COMMENTED** [review]
For now, let's keep this, we have a lot of work to do, some classes will disappear others will be created... Let's think about it later.

**Comment by PILOTEZEBS** [comment]
ok

**Comment by FanJups** [comment]
Finally, we'll not add.

**Pull request closed without merging**
